name: Deploy
on:
  push:
    branches:
      - master

jobs:
  mkdocs:
    name: MkDocs
    runs-on: ubuntu-latest
    if: github.repository == 'go-rel/doc'
    steps:
      - name: Checkout doc
        uses: actions/checkout@v2
        with:
          path: doc
      - name: Checkout site
        uses: actions/checkout@v2
        with:
          repository: go-rel/go-rel.github.io
          token: ${{ secrets.PERSONAL_TOKEN }}
          path: site
      - uses: actions/setup-python@v1
        with:
          python-version: 3.9
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.21
      - name: Install mkdocs and its plugins
        working-directory: doc
        run: |
          pip install \
            'requests' \
            'jinja2==3.0.3' \
            'mkdocs==1.1.2' \
            'mkdocs-material==6.0.0' \
            'mkdocs-material-extensions==1.0.1' \
            'mkdocs-minify-plugin==0.3.0' \
            'mkdocs-macros-plugin==0.4.15' \
            'mkdocs-git-revision-date-plugin==0.3' \
            'mkdocs-meta-descriptions-plugin===1.0.2'
      - name: Install godoc2md
        working-directory: doc
        run: |
          go get github.com/Yarn-e/godoc2md
          go install github.com/Yarn-e/godoc2md
      - name: Build site
        working-directory: doc
        env:
          GOOGLE_ANALYTICS_KEY: ${{ secrets.GOOGLE_ANALYTICS_KEY }}
        run: |
          mkdocs --version
          mkdocs build
      - name: Push site
        working-directory: site
        run: |
          yes | cp -rf ../doc/site/* .
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "deploy ${GITHUB_SHA}"
          git push
