name: Deploy
on:
  push:
    branches:
      - master

jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.15
      - run: go test -race ./...

  mkdocs:
    name: mkdocs
    runs-on: ubuntu-latest
    if: github.repository == 'go-rel/doc'
    needs: test
    steps:
      - name: Checkout doc
        uses: actions/checkout@v2
        with:
          path: doc
      - name: Checkout site
        uses: actions/checkout@v2
        with:
          repository: go-rel/go-rel.github.io
          token: ${{ secrets.PERSONAL_TOKEN }}
          path: site
      - uses: actions/setup-python@v1
        with:
          python-version: 3.x
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.15
      - name: Install mkdocs and it's plugins
        working-directory: doc
        run: |
          pip install \
            'requests' \
            'mkdocs==1.1.2' \
            'mkdocs-material==6.0.0' \
            'mkdocs-material-extensions==1.0.1' \
            'mkdocs-minify-plugin==0.3.0' \
            'mkdocs-macros-plugin==0.4.15' \
            'mkdocs-git-revision-date-plugin==0.3'
      - name: Install godoc2md
        working-directory: doc
        run: go get github.com/davecheney/godoc2md
      - name: Build site
        working-directory: doc
        env:
          GOOGLE_ANALYTICS_KEY: ${{ secrets.GOOGLE_ANALYTICS_KEY }}
        run: |
          mkdocs --version
          mkdocs build
      - name: Push site
        working-directory: site
        run: |
          yes | cp -rf ../rel/site/* .
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "deploy ${GITHUB_SHA}"
          git push
